<a href="https://colab.research.google.com/github/lricci03/challengedata/blob/main/CFM2024-new/create_submission.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Create submission

This is a template to create the submission file for the challenge.

The submission is a csv file containing the prediction for the test set.

Workflow:

Once we have finished model selection:
- Upload the full train set and preprocess it;
- retrain the chosen architecture on the full training set;
- Upload the test set, and preprocessed;
- predict on test.

In [ ]:
import torch
import torch.nn as nn

if torch.cuda.is_available():
  device = 'cuda'
elif torch.backends.mps.is_available():
  device = 'mps'
else:
  device = 'cpu'

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive

# drive.flush_and_unmount()
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Upload the full train set

### Train set sequential features

In [ ]:
from pathlib import Path

path = Path("/content/drive/MyDrive/Challengedata/Xtrain.parquet")

df_features = pd.read_parquet(path)

df_features.head()

,obs_id,venue,order_id,action,side,price,bid,ask,bid_size,ask_size,trade,flux
0,0,4,0,A,A,0.30,0.0,0.01,100,1,False,100
1,0,4,1,A,B,-0.17,0.0,0.01,100,1,False,100
2,0,4,2,D,A,0.28,0.0,0.01,100,1,False,-100
3,0,4,3,A,A,0.30,0.0,0.01,100,1,False,100
4,0,4,4,D,A,0.37,0.0,0.01,100,1,False,-100

In [ ]:
df_targets = pd.read_csv("/content/drive/MyDrive/Challengedata/y_train_or6m3Ta.csv")

df_targets.head()

   obs_id  eqt_code_cat
0       0            10
1       1            15
2       2             0
3       3            13
4       4             0

In [ ]:
def add_order_features(df):

    # how many previous events involved this same order
    df["order_previous_count"] = (
        df.groupby(["obs_id", "order_id"])
          .cumcount()
          .astype("float32")
    )

    # whether this order was seen before
    df["order_seen_before"] = (
        df["order_previous_count"] > 0
    ).astype("float32")

    # raw ID no longer needed
    df.drop("order_id", axis=1, inplace=True)

    return df

In [ ]:
df_features = add_order_features(df_features)

In [ ]:
df_features = df_features[[
    "obs_id",
    "price", "bid", "ask",
    "bid_size", "ask_size",
    "flux",
    "action", "venue", "side", "trade",
    "order_previous_count",
    "order_seen_before"
]]

In [ ]:
num_attribs = ['price', 'bid', 'ask', 'bid_size', 'ask_size', 'flux', 'trade', 'order_seen_before', 'order_previous_count']
cat_attribs = ['venue', 'action', 'side']

In [ ]:
df_features[num_attribs] = df_features[num_attribs].astype("float32")

In [ ]:
df_features = pd.get_dummies(df_features, columns=cat_attribs, dtype="float32")

In [ ]:
df_features = df_features.set_index("obs_id")
df_targets = df_targets.set_index("obs_id")

In [ ]:
n_features = df_features.shape[1]

print(n_features)

20

Convert to tensors

In [ ]:
X_seq = torch.tensor(
    df_features.to_numpy(dtype=np.float32),
    dtype=torch.float32
).reshape(-1, 100, n_features)

y_train_full = torch.tensor(
    df_targets["eqt_code_cat"].to_numpy(),
    dtype=torch.long
)

In [ ]:
import gc

del df_features, df_targets
gc.collect()

255

### Train set engineered features

In [ ]:
df_eng = pd.read_csv("/content/drive/MyDrive/Challengedata/eng_features.csv")

In [ ]:
df_eng = df_eng.set_index("obs_id")

In [ ]:
X_eng = torch.tensor(df_eng.values, dtype=torch.float32)

In [ ]:
mean = X_eng.mean(dim=0, keepdim=True)
std = X_eng.std(dim=0, keepdim=True)

# avoid division by zero for constant features
std[std == 0] = 1.0

X_eng_std = (X_eng - mean) / std

## Datasets and DataLoaders

### Sequential + Engineered features

Dataset to combine sequential and engineered features

In [ ]:
from torch.utils.data import Dataset
import torch

class StockDataset(Dataset):
    def __init__(self, X_seq, X_eng, y):
        self.X_seq = X_seq
        self.X_eng = X_eng
        self.y = y

    def __len__(self):
        return len(self.y)

    def __getitem__(self, idx):
        return (
            self.X_seq[idx],
            self.X_eng[idx],
            self.y[idx]
        )

In [ ]:
train_dataset = StockDataset(X_seq, X_eng, y_train_full)

In [ ]:
from torch.utils.data import DataLoader

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)

### Sequential features only

In [ ]:
from torch.utils.data import TensorDataset, DataLoader

train_dataset_seq = TensorDataset(X_seq, y_train_full)
train_loader_seq = DataLoader(train_dataset_seq, batch_size=64, shuffle=True)

## Train function

We don't need the validation and the best model logic we used during model selection.

We train on the number of epochs we selected during model selection.

**Train function for sequential data only**

In [ ]:
%pip install -q torchmetrics

In [ ]:
import torchmetrics


def train_full(model, optimizer, loss_fn, metric, train_loader, n_epochs):

    history = {
        "train_losses": [],
        "train_metrics": []
    }

    for epoch in range(n_epochs):
        total_loss = 0.0
        metric.reset()
        model.train()

        for X_batch, y_batch in train_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)

            y_pred = model(X_batch)
            loss = loss_fn(y_pred, y_batch)

            total_loss += loss.item()

            loss.backward()
            optimizer.step()
            optimizer.zero_grad()

            y_class = y_pred.detach().argmax(dim=1)
            metric.update(y_class, y_batch)

        train_loss = total_loss / len(train_loader)
        train_metric = metric.compute().item()

        history["train_losses"].append(train_loss)
        history["train_metrics"].append(train_metric)

        print(
            f"Epoch {epoch + 1}/{n_epochs}, "
            f"train loss: {train_loss:.4f}, "
            f"train metric: {train_metric:.4f}"
        )

    return history

**Train function for joint model**

In [ ]:
def train_full_joint(model, optimizer, loss_fn, metric, train_loader, n_epochs):

    history = {
        "train_losses": [],
        "train_metrics": []
    }

    for epoch in range(n_epochs):
        total_loss = 0.0
        metric.reset()
        model.train()

        for X_seq_batch, X_eng_batch, y_batch in train_loader:
            X_seq_batch = X_seq_batch.to(device)
            X_eng_batch = X_eng_batch.to(device)
            y_batch = y_batch.to(device)

            optimizer.zero_grad()

            y_pred = model(X_seq_batch, X_eng_batch)
            loss = loss_fn(y_pred, y_batch)

            total_loss += loss.item()

            loss.backward()
            optimizer.step()

            y_class = y_pred.detach().argmax(dim=1)
            metric.update(y_class, y_batch)

        train_loss = total_loss / len(train_loader)
        train_metric = metric.compute().item()

        history["train_losses"].append(train_loss)
        history["train_metrics"].append(train_metric)

        print(
            f"Epoch {epoch + 1}/{n_epochs}, "
            f"train loss: {train_loss:.4f}, "
            f"train metric: {train_metric:.4f}"
        )

    return history

## Train on the full training set

#### Deep GRU

The best model is a Deep GRU (2 gru layers) that we trained on the sequential features only (so not joint), and the features are not normalized.

It is saved as `deep_gru_model_128.pt`

In [ ]:
class DeepGRUModel(nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super().__init__()
    self.hidden_size = hidden_size
    self.rnn = nn.GRU(input_size, hidden_size, num_layers=2, batch_first=True)
    self.output = nn.Linear(hidden_size, output_size)

  def forward(self,X):
    outputs, last_state = self.rnn(X)
    return self.output(outputs[:, -1])

In [ ]:
torch.manual_seed(42)

model = DeepGRUModel(input_size=20, hidden_size=128, output_size=24).to(device)

optimizer = torch.optim.NAdam(model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=24).to(device)

history = train_full(model, optimizer, criterion, accuracy, train_loader_seq, 60)

Epoch 1/60, train loss: 2.7403, train metric: 0.1220
Epoch 2/60, train loss: 2.5478, train metric: 0.1675
Epoch 3/60, train loss: 2.4655, train metric: 0.1878
Epoch 4/60, train loss: 2.3962, train metric: 0.2051
Epoch 5/60, train loss: 2.3373, train metric: 0.2213
Epoch 6/60, train loss: 2.2812, train metric: 0.2392
Epoch 7/60, train loss: 2.2084, train metric: 0.2633
Epoch 8/60, train loss: 2.1400, train metric: 0.2861
Epoch 9/60, train loss: 2.0864, train metric: 0.3023
Epoch 10/60, train loss: 2.0352, train metric: 0.3183
Epoch 11/60, train loss: 1.9863, train metric: 0.3330
Epoch 12/60, train loss: 1.9401, train metric: 0.3499
Epoch 13/60, train loss: 1.8972, train metric: 0.3636
Epoch 14/60, train loss: 1.8566, train metric: 0.3768
Epoch 15/60, train loss: 1.8172, train metric: 0.3914
Epoch 16/60, train loss: 1.7819, train metric: 0.4019
Epoch 17/60, train loss: 1.7486, train metric: 0.4128
Epoch 18/60, train loss: 1.7159, train metric: 0.4233
Epoch 19/60, train loss: 1.6862, train metric: 0.4324
Epoch 20/60, train loss: 1.6571, train metric: 0.4423
Epoch 21/60, train loss: 1.6299, train metric: 0.4503
Epoch 22/60, train loss: 1.6020, train metric: 0.4614
Epoch 23/60, train loss: 1.5766, train metric: 0.4680
Epoch 24/60, train loss: 1.5492, train metric: 0.4776
Epoch 25/60, train loss: 1.5217, train metric: 0.4882
Epoch 26/60, train loss: 1.4950, train metric: 0.4966
Epoch 27/60, train loss: 1.4706, train metric: 0.5039
Epoch 28/60, train loss: 1.4459, train metric: 0.5126
Epoch 29/60, train loss: 1.4212, train metric: 0.5198
Epoch 30/60, train loss: 1.3998, train metric: 0.5264
Epoch 31/60, train loss: 1.3779, train metric: 0.5350
Epoch 32/60, train loss: 1.3583, train metric: 0.5413
Epoch 33/60, train loss: 1.3394, train metric: 0.5464
Epoch 34/60, train loss: 1.3206, train metric: 0.5535
Epoch 35/60, train loss: 1.3029, train metric: 0.5577
Epoch 36/60, train loss: 1.2864, train metric: 0.5642
Epoch 37/60, train loss: 1.2695, train metric: 0.5696
Epoch 38/60, train loss: 1.2543, train metric: 0.5741
Epoch 39/60, train loss: 1.2392, train metric: 0.5790
Epoch 40/60, train loss: 1.2238, train metric: 0.5847
Epoch 41/60, train loss: 1.2101, train metric: 0.5898
Epoch 42/60, train loss: 1.1961, train metric: 0.5929
Epoch 43/60, train loss: 1.1825, train metric: 0.5975
Epoch 44/60, train loss: 1.1697, train metric: 0.6011
Epoch 45/60, train loss: 1.1572, train metric: 0.6061
Epoch 46/60, train loss: 1.1456, train metric: 0.6104
Epoch 47/60, train loss: 1.1337, train metric: 0.6136
Epoch 48/60, train loss: 1.1232, train metric: 0.6163
Epoch 49/60, train loss: 1.1116, train metric: 0.6209
Epoch 50/60, train loss: 1.1017, train metric: 0.6229
Epoch 51/60, train loss: 1.0910, train metric: 0.6271
Epoch 52/60, train loss: 1.0808, train metric: 0.6301
Epoch 53/60, train loss: 1.0710, train metric: 0.6338
Epoch 54/60, train loss: 1.0623, train metric: 0.6365
Epoch 55/60, train loss: 1.0530, train metric: 0.6400
Epoch 56/60, train loss: 1.0435, train metric: 0.6431
Epoch 57/60, train loss: 1.0352, train metric: 0.6449
Epoch 58/60, train loss: 1.0245, train metric: 0.6489
Epoch 59/60, train loss: 1.0179, train metric: 0.6512
Epoch 60/60, train loss: 1.0089, train metric: 0.6538

Save the model weights

In [ ]:
torch.save(
    model.state_dict(),
    "/content/drive/MyDrive/Challengedata/best_model.pt"
)

In [ ]:
del X_seq, y_train_full, train_dataset_seq, train_loader_seq
gc.collect()

8

#### Stacked Deep Gru Inception

##### Scale numerical features for Inception module

We need to scale the numerical features.

In [ ]:
num_idx = slice(0, 9)

mean = X_seq[:, :, num_idx].mean(dim=(0, 1), keepdim=True)
std = X_seq[:, :, num_idx].std(dim=(0, 1), keepdim=True)

X_seq[:, :, num_idx] = (
    X_seq[:, :, num_idx] - mean
) / (std + 1e-8)

Check

In [ ]:
train_dataset_seq.tensors[0] is X_seq

True

In [ ]:
from torch.nn.modules.pooling import MaxPool1d

class InceptionModule(nn.Module):
  def __init__(self, n_inputs):
    super().__init__()
    self.conv0 = nn.Sequential(
        nn.Conv1d(in_channels=n_inputs, out_channels=64, kernel_size=1, padding='same'), nn.ReLU())
    self.conv1 = nn.Sequential(
        nn.Conv1d(in_channels=n_inputs, out_channels=64, kernel_size=1, padding='same'), nn.ReLU(),
        nn.Conv1d(in_channels=64, out_channels=128, kernel_size=3, padding='same'), nn.ReLU())
    self.conv2 = nn.Sequential(
        nn.Conv1d(in_channels=n_inputs, out_channels=16, kernel_size=1, padding='same'), nn.ReLU(),
        nn.Conv1d(in_channels=16, out_channels=48, kernel_size=5, padding='same'), nn.ReLU())
    self.conv3 = nn.Sequential(
        nn.MaxPool1d(kernel_size=3, stride=1, padding=1), # stride=1, padding=1 (this depends on kernel_size=3) so the in & out have same dim
        nn.Conv1d(in_channels=n_inputs, out_channels=48, kernel_size=1, padding='same'), nn.ReLU())

  def forward(self,X):
    return torch.cat([self.conv0(X), self.conv1(X), self.conv2(X), self.conv3(X)], dim=1)

In [ ]:
class InceptionGRUModel(nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super().__init__()
    self.incep = nn.Sequential(
      InceptionModule(n_inputs=input_size),
      nn.MaxPool1d(kernel_size=2), # this divides the height and width by 2
      InceptionModule(288),          # -> 288 channels
      nn.MaxPool1d(2)
      )
    self.gru = nn.GRU(
      input_size=288,
      hidden_size=hidden_size,
      num_layers=2,
      batch_first=True
      )
    self.output = nn.Linear(in_features = hidden_size, out_features = output_size)

  def forward(self,X):
    Z = X.permute(0,2,1)  # treat ticks as spatial dimension
    Z = self.incep(Z)     # (B, 288, 25)
    Z = Z.permute(0, 2, 1) # (B, 25, 288)

    outputs, _ = self.gru(Z)
    return self.output(outputs[:, -1])

In [ ]:
torch.manual_seed(42)

model = InceptionGRUModel(input_size=20, hidden_size=128, output_size=24).to(device)

optimizer = torch.optim.NAdam(model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=24).to(device)

history = train_full(model, optimizer, criterion, accuracy, train_loader_seq, 60)

Epoch 1/60, train loss: 2.5874, train metric: 0.1504
Epoch 2/60, train loss: 2.2989, train metric: 0.2424
Epoch 3/60, train loss: 2.1471, train metric: 0.2878
Epoch 4/60, train loss: 2.0403, train metric: 0.3199
Epoch 5/60, train loss: 1.9536, train metric: 0.3457
Epoch 6/60, train loss: 1.8868, train metric: 0.3670
Epoch 7/60, train loss: 1.8318, train metric: 0.3826
Epoch 8/60, train loss: 1.7833, train metric: 0.3977
Epoch 9/60, train loss: 1.7394, train metric: 0.4117
Epoch 10/60, train loss: 1.6996, train metric: 0.4233
Epoch 11/60, train loss: 1.6611, train metric: 0.4353
Epoch 12/60, train loss: 1.6242, train metric: 0.4455
Epoch 13/60, train loss: 1.5897, train metric: 0.4577
Epoch 14/60, train loss: 1.5551, train metric: 0.4692
Epoch 15/60, train loss: 1.5230, train metric: 0.4804
Epoch 16/60, train loss: 1.4923, train metric: 0.4905
Epoch 17/60, train loss: 1.4651, train metric: 0.4977
Epoch 18/60, train loss: 1.4384, train metric: 0.5073
Epoch 19/60, train loss: 1.4119, train metric: 0.5162
Epoch 20/60, train loss: 1.3889, train metric: 0.5235
Epoch 21/60, train loss: 1.3650, train metric: 0.5312
Epoch 22/60, train loss: 1.3450, train metric: 0.5379
Epoch 23/60, train loss: 1.3232, train metric: 0.5460
Epoch 24/60, train loss: 1.3030, train metric: 0.5527
Epoch 25/60, train loss: 1.2835, train metric: 0.5582
Epoch 26/60, train loss: 1.2643, train metric: 0.5649
Epoch 27/60, train loss: 1.2468, train metric: 0.5713
Epoch 28/60, train loss: 1.2292, train metric: 0.5768
Epoch 29/60, train loss: 1.2120, train metric: 0.5830
Epoch 30/60, train loss: 1.1953, train metric: 0.5888
Epoch 31/60, train loss: 1.1794, train metric: 0.5930
Epoch 32/60, train loss: 1.1631, train metric: 0.5983
Epoch 33/60, train loss: 1.1479, train metric: 0.6027
Epoch 34/60, train loss: 1.1330, train metric: 0.6083
Epoch 35/60, train loss: 1.1179, train metric: 0.6136
Epoch 36/60, train loss: 1.1055, train metric: 0.6177
Epoch 37/60, train loss: 1.0904, train metric: 0.6222
Epoch 38/60, train loss: 1.0753, train metric: 0.6273
Epoch 39/60, train loss: 1.0627, train metric: 0.6322
Epoch 40/60, train loss: 1.0496, train metric: 0.6348
Epoch 41/60, train loss: 1.0358, train metric: 0.6395
Epoch 42/60, train loss: 1.0242, train metric: 0.6446
Epoch 43/60, train loss: 1.0127, train metric: 0.6476
Epoch 44/60, train loss: 1.0001, train metric: 0.6528
Epoch 45/60, train loss: 0.9894, train metric: 0.6549
Epoch 46/60, train loss: 0.9755, train metric: 0.6600
Epoch 47/60, train loss: 0.9654, train metric: 0.6627
Epoch 48/60, train loss: 0.9535, train metric: 0.6686
Epoch 49/60, train loss: 0.9435, train metric: 0.6710
Epoch 50/60, train loss: 0.9331, train metric: 0.6750
Epoch 51/60, train loss: 0.9224, train metric: 0.6779
Epoch 52/60, train loss: 0.9123, train metric: 0.6814
Epoch 53/60, train loss: 0.9016, train metric: 0.6846
Epoch 54/60, train loss: 0.8906, train metric: 0.6895
Epoch 55/60, train loss: 0.8813, train metric: 0.6920
Epoch 56/60, train loss: 0.8712, train metric: 0.6953
Epoch 57/60, train loss: 0.8622, train metric: 0.6986
Epoch 58/60, train loss: 0.8525, train metric: 0.7016
Epoch 59/60, train loss: 0.8414, train metric: 0.7048
Epoch 60/60, train loss: 0.8323, train metric: 0.7079

## Preprocessing of the test set

In [ ]:
path = Path("/content/drive/MyDrive/Challengedata/Xtest.parquet")

df_test = pd.read_parquet(path)

In [ ]:
df_test = add_order_features(df_test)

In [ ]:
df_test = df_test[[
    "obs_id",
    "price", "bid", "ask",
    "bid_size", "ask_size",
    "flux",
    "action", "venue", "side", "trade",
    "order_previous_count",
    "order_seen_before"
]]

In [ ]:
num_attribs = ['price', 'bid', 'ask', 'bid_size', 'ask_size', 'flux', 'trade', 'order_seen_before', 'order_previous_count']
cat_attribs = ['venue', 'action', 'side']

In [ ]:
df_test[num_attribs] = df_test[num_attribs].astype("float32")

In [ ]:
df_test = pd.get_dummies(df_test, columns=cat_attribs, dtype="float32")

In [ ]:
df_test = df_test[df_features.columns]

In [ ]:
df_test = df_test.set_index("obs_id")

KeyError: "None of ['obs_id'] are in the columns"

In [ ]:
print(df_features.columns.equals(df_test.columns))

print(df_features.columns.tolist())
print(df_test.columns.tolist())

NameError: name 'df_features' is not defined

In [ ]:
X_test_seq = torch.tensor(
    df_test.to_numpy(dtype=np.float32),
    dtype=torch.float32
).reshape(-1, 100, n_features)

In [ ]:
test_dataset = TensorDataset(X_test_seq)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

Scale the test set with the train set parameters

In [ ]:
X_test_seq[:, :, num_idx] = (
    X_test_seq[:, :, num_idx] - mean
) / (std + 1e-8)

## Predict

In [ ]:
model.eval()

predictions = []

with torch.no_grad():
    for (X_batch,) in test_loader:
        X_batch = X_batch.to(device)

        logits = model(X_batch)
        y_pred = logits.argmax(dim=1)

        predictions.extend(y_pred.cpu().numpy())

Save the predictions in csv

In [ ]:
submission = pd.DataFrame({
    "obs_id": range(len(predictions)),
    "eqt_code_cat": predictions
})

submission.to_csv(
    "/content/drive/MyDrive/Challengedata/submission4.csv",
    index=False
)