<a href="https://colab.research.google.com/github/lricci03/challengedata/blob/main/cfm2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

if torch.cuda.is_available():
  device = 'cuda'
elif torch.backends.mps.is_available():
  device = 'mps'
else:
  device = 'cpu'

In [2]:
import pandas as pd

In [3]:
from google.colab import drive

drive.flush_and_unmount()
drive.mount("/content/drive", force_remount=True)

Drive not mounted, so nothing to flush and unmount.
Mounted at /content/drive

In [4]:
from pathlib import Path

DATA_DIR = Path(
    "/content/drive/MyDrive/Challengedata"
)

print(DATA_DIR.exists())

True

The original csv file is 1.2GB. Locally in CSV we convert it into a parquet file

```
import duckdb

# convert X_train_N1UvY30.csv into Xtrain.parquet
duckdb.sql("""
COPY (
    SELECT *
    FROM read_csv_auto('../X_train_N1UvY30.csv')
)
TO 'Xtrain.parquet'
(FORMAT PARQUET, COMPRESSION ZSTD);
""")
```

Look at the data

In [6]:
path = Path("/content/drive/MyDrive/Challengedata/Xtrain.parquet")

df = pd.read_parquet(path)

df[:10]

,obs_id,venue,order_id,action,side,price,bid,ask,bid_size,ask_size,trade,flux
0,0,4,0,A,A,0.30,0.0,0.01,100,1,False,100
1,0,4,1,A,B,-0.17,0.0,0.01,100,1,False,100
2,0,4,2,D,A,0.28,0.0,0.01,100,1,False,-100
3,0,4,3,A,A,0.30,0.0,0.01,100,1,False,100
4,0,4,4,D,A,0.37,0.0,0.01,100,1,False,-100
5,0,1,5,D,A,0.05,0.0,0.01,100,1,False,-1
6,0,4,6,A,B,-0.19,0.0,0.01,100,1,False,100
7,0,4,1,D,B,-0.17,0.0,0.01,100,1,False,-100
8,0,4,3,D,A,0.30,0.0,0.01,100,1,False,-100
9,0,4,7,A,B,-0.02,0.0,0.01,100,1,False,1

In [10]:
df.shape

(16080000, 12)

In [13]:
# Filters for order_id 8, then grabs the first 100 results
print(df[df['order_id'] == 8].head(20))

     obs_id  venue  order_id action side  price   bid   ask  bid_size  \
10        0      4         8      A    B  -0.02  0.00  0.01       100
16        0      4         8      D    B  -0.02  0.00  0.01       100
109       1      4         8      D    A   0.06  0.00  0.04         2
209       2      4         8      A    B  -0.01  0.00  0.01       740
224       2      4         8      D    B  -0.01  0.00  0.01      1310
311       3      2         8      A    A   0.21  0.00  0.20       683
313       3      2         8      D    A   0.21  0.00  0.20       683
408       4      4         8      A    B   0.01  0.01  0.02       245
509       5      4         8      A    A   0.02 -0.01  0.02       147
554       5      4         8      D    A   0.02 -0.01  0.01       109
609       6      5         8      D    A   9.37  0.00  0.02       290
610       6      5         8      A    A   9.36  0.00  0.02       290
626       6      5         8      D    A   9.36  0.00  0.01       300
627       6      5         8      A    A   9.37  0.00  0.01       300
632       6      5         8      D    A   9.37  0.00  0.01       200
633       6      5         8      A    A   9.36  0.00  0.01       200
663       6      5         8      D    A   9.36  0.00  0.02       410
664       6      5         8      A    A   9.37  0.00  0.02       410
665       6      5         8      D    A   9.37  0.00  0.02       410
666       6      5         8      A    A   9.36  0.00  0.02       410

     ask_size  trade  flux
10          1  False   100
16          1  False  -100
109        75  False   -76
209      2300  False   100
224       700  False  -100
311        20  False   100
313        20  False  -100
408       300  False    45
509       240  False    10
554       103  False   -10
609       705  False  -100
610       705  False   100
626       110  False  -100
627       110  False   100
632       220  False  -100
633       220  False   100
663       400  False  -100
664       400  False   100
665       400  False  -100
666       400  False   100

In [ ]:
targets = pd.read_csv("/content/drive/MyDrive/Challengedata/y_train_or6m3Ta.csv")

targets.head()

   obs_id  eqt_code_cat
0       0            10
1       1            15
2       2             0
3       3            13
4       4             0